services:
    zookeeper:
        image: confluentinc/cp-zookeeper:5.5.1
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:5.5.1
        hostname: kafka
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        volumes:
            - type: bind
              source: "./jmx_prometheus_javaagent-0.17.2.jar"
              target: /opt/jmx-exporter/jmx_prometheus_javaagent-0.17.2.jar
              read_only: true
            - type: bind
              source: "./kafka-broker.yml"
              target: /opt/jmx-exporter/kafka-broker.yml
              read_only: true
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_NUM_PARTITIONS: 5
            KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 5
            KAFKA_DEFAULT_REPLICATION_FACTOR: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_MIN_INSYNC_REPLICAS: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_OPTS: '-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.17.2.jar=9101:/opt/jmx-exporter/kafka-broker.yml'
            CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'

    conduktor-platform:
        image: conduktor/conduktor-platform:1.4.0
        ports:
            - 8080:8080
        depends_on:
            - kafka
        environment:
            KAFKA_BOOTSTRAP_SERVER: kafka:29092
            ORGANISATION_NAME: "default"
            ADMIN_EMAIL: "admin@admin.io"
            ADMIN_PSW: "admin"
