spring:
    application:
        name: kafka-demo

server:
    port: 9001

kafka:
    bootstrap-servers: localhost:9092
    producer:
        lingerMs: 0
    consumer:
        maxPollIntervalMs: 30000
        maxPollRecordsMs: 500

kafkademo:
    outboundTopic : "demo-topic"
